# Generated by Django 2.1.1 on 2018-09-01 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=256)),
                ('date', models.DateTimeField(verbose_name='Invoice Date')),
                ('invoice_number', models.IntegerField()),
                ('total_quantity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_tax', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=256)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('price_without_tax', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tax_name', models.CharField(max_length=256)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Invoice')),
            ],
        ),
    ]
